=== prompt-native/prompt-schema/schema/chat-schema-0.4.json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "description": "The schema version"
    },
    "engine": {
      "type": "string",
      "description": "Model engine that is expected to use"
    },
    "context": {
      "type": "string",
      "description": "Context instructs how the model should respond. For example, “Explain this code,” specifying words the model can or cannot use, topics to focus on or avoid, or response format. Context applies each time you send a request to the model."
    },
    "examples": {
      "type": "array",
      "minItems": 1,
      "description": "Examples help the model understand what an appropriate model response looks like. You can write your own example input and output or use the Test section to save a real response as an example. You can also add a prefix which will be appended to every example (for instance, “question” and “answer”).",
      "items": {
        "$ref": "#/definitions/message"
      }
    },
    "messages": {
      "type": "array",
      "minItems": 1,
      "description": "History messages in the conversation",
      "items": {
        "$ref": "#/definitions/message"
      }
    },
    "parameters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameter"
      },
      "description": "LLM parameters."
    }
  },
  "required": [
    "version",
    "engine",
    "messages"
  ],
  "definitions": {
    "message": {
      "properties": {
        "role": {
          "type": "string",
          "enum": [
            "user",
            "assistant",
            "function"
          ],
          "description": "Role of this message"
        },
        "name": {
          "type": "string",
          "description": "The name of this participant"
        },
        "content": {
          "type": "string",
          "description": "The message content"
        },
        "function_call": {
          "$ref": "#/definitions/functionCall"
        }
      },
      "oneOf": [
        {
          "required": [
            "role",
            "content"
          ]
        },
        {
          "required": [
            "role",
            "function_call"
          ]
        }
      ]
    },
    "functionCall": {
      "properties": {
        "name": {
          "type": "string",
          "description": "Function name"
        },
        "arguments": {
          "type": "string",
          "description": "Function call arguments(serialized in JSON)"
        }
      },
      "required": [
        "name",
        "arguments"
      ]
    },
    "parameter": {
      "additionalProperties ": false,
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-z]+(_[a-z]+)*$",
          "description": "Name of parameter"
        },
        "value": {
          "type": [
            "string",
            "number",
            "boolean"
          ],
          "description": "Value of this parameter"
        }
      },
      "required": [
        "name",
        "value"
      ]
    }
  }
}

=== prompt-native/prompt-schema/json-examples/pass-chat4-with-context.json
{
  "$schema": "../schema/chat-schema-0.4.json",
  "version": "0.2",
  "engine": "chat-bison",
  "context": "Assume that you are a calculator",
  "examples": [
    {
      "role": "user",
      "content": "1+1"
    },
    {
      "role": "assistant",
      "content": "=2"
    }
  ],
  "messages": [
    {
      "role": "user",
      "content": "2*4"
    }
  ],
  "parameters": [
    {
      "name": "temperature",
      "value": 0.1
    }
  ]
}

=== prompt-native/prompt-schema/json-examples/pass-chat3-with-examples.json
{
  "$schema": "../schema/chat-schema-0.4.json",
  "version": "0.2",
  "engine": "chat-bison",
  "examples": [
    {
      "role": "user",
      "content": "1+1"
    },
    {
      "role": "assistant",
      "content": "=2"
    }
  ],
  "messages": [
    {
      "role": "user",
      "content": "2*4"
    }
  ],
  "parameters": [
    {
      "name": "temperature",
      "value": 0.1
    }
  ]
}

=== prompt-native/prompt-schema/json-examples/pass-chat8-with-function.json
{
  "$schema": "../schema/chat-schema.json",
  "version": "0.3",
  "engine": "chat-bison",
  "messages": [
    {
      "role": "user",
      "content": "What is the weather today in Beijing?"
    },
    {
      "role": "assistant",
      "function_call": {
				"name": "get_weather",
				"arguments": "{\n\"city\": \"Beijing\",\n\"time\": \"today\"\n}"
			}
    },
    {
			"role": "function",
			"name": "get_weather",
			"content": "{\"weather\": \"sunny, 25C\"}"
		}
  ],
  "parameters": [
    {
      "name": "temperature",
      "value": 0.1
    }
  ]
}
