=== prompt-native/prompt-schema/schema/chat-schema-0.3.json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "description": "The schema version, currently is 0.2"
    },
    "type": {
      "type": "string",
      "enum": [
        "chat"
      ],
      "markdownDescription": "Define the prompt type. You can use:\n * `chat`: prompt used to initiate open-ended conversations with LLM\n * `completion`: prompt used to guide users towards specific actions or responses"
    },
    "vendor": {
      "type": "string",
      "description": "The provider of the model used in this prompt"
    },
    "model": {
      "$ref": "#/definitions/model",
      "description": "The LLM model, eg. text-bison or gpt-3.5-turbo"
    },
    "context": {
      "type": "string",
      "description": "Context instructs how the model should respond. For example, “Explain this code,” specifying words the model can or cannot use, topics to focus on or avoid, or response format. Context applies each time you send a request to the model."
    },
    "examples": {
      "type": "array",
      "minItems": 1,
      "description": "Examples help the model understand what an appropriate model response looks like. You can write your own example input and output or use the Test section to save a real response as an example. You can also add a prefix which will be appended to every example (for instance, “question” and “answer”).",
      "items": {
        "$ref": "#/definitions/message"
      }
    },
    "messages": {
      "type": "array",
      "minItems": 1,
      "description": "History messages in the conversation",
      "items": {
        "$ref": "#/definitions/message"
      }
    },
    "parameters": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/parameter"
      },
      "description": "LLM parameters."
    }
  },
  "required": [
    "version",
    "type",
    "vendor",
    "model"
  ],
  "definitions": {
    "message": {
      "properties": {
        "role": {
          "type": "string",
          "enum": [
            "user",
            "assistant",
            "function"
          ],
          "description": "Role of this message"
        },
        "name": {
          "type": "string",
          "description": "The name of this participant"
        },
        "content": {
          "type": "string",
          "description": "The message content"
        },
        "function_call": {
          "$ref": "#/definitions/functionCall"
        }
      },
      "oneOf": [
        {
          "required": [
            "role",
            "content"
          ]
        },
        {
          "required": [
            "role",
            "function_call"
          ]
        }
      ]
    },
    "functionCall": {
      "properties": {
        "name": {
          "type": "string",
          "description": "Function name"
        },
        "arguments": {
          "type": "string",
          "description": "Function call arguments(serialized in JSON)"
        }
      },
      "required": [
        "name",
        "arguments"
      ]
    },
    "parameter": {
      "additionalProperties ": false,
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-z]+(_[a-z]+)*$",
          "description": "Name of parameter"
        },
        "value": {
          "type": [
            "string",
            "number",
            "boolean"
          ],
          "description": "Value of this parameter"
        }
      },
      "required": [
        "name",
        "value"
      ]
    },
    "model": {
      "additionalProperties ": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of parameter"
        },
        "version": {
          "type": "string",
          "description": "Additional version information of the model. For example, if you are using text-bison@001, then you can set modelVersion to 001"
        }
      },
      "required": [
        "name"
      ]
    }
  }
}

=== prompt-native/prompt-schema/json-examples/pass-chat6-with-model-version.json
{
  "$schema": "../schema/chat-schema-0.3.json",
  "version": "0.2",
  "type": "chat",
  "vendor": "google",
  "model": {
    "name": "chat-bison",
    "version": "002"
  },
  "messages": [
    {
      "role": "user",
      "content": "Write a hello world in js"
    }
  ],
  "parameters": [
    {
      "name": "temperature",
      "value": 0.1
    }
  ]
}

=== prompt-native/prompt-schema/json-examples/pass-chat2-multi-turn.json
{
  "$schema": "../schema/chat-schema-0.3.json",
  "version": "0.2",
  "type": "chat",
  "vendor": "google",
  "model": {
    "name": "chat-bison"
  },
  "messages": [
    {
      "role": "user",
      "content": "Write a hello world in js"
    },
    {
      "role": "assistant",
      "content": "console.log('Hello world!')"
    },
    {
      "role": "user",
      "content": "Can you change it into python?"
    }
  ],
  "parameters": [
    {
      "name": "temperature",
      "value": 0.1
    }
  ]
}
